# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Swift5ShindanMaker1' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Swift5ShindanMaker1

  pod 'Firebase/Firestore'
  pod 'Firebase/Auth'
  pod 'BubbleTransition', '~> 3.2.0'
  pod 'SDWebImage', '~> 5.0'
  pod 'ViewAnimator'
  pod 'NVActivityIndicatorView'

end
